// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`GitHubSearchStreamRepository #findByQuery when exist stream json for query, it should return stream json 1`] = `
Array [
  Object {
    "assignee": null,
    "assignees": Array [],
    "body": "Originally reported by: **@wyuenho**

---

So apparently Tree.mount() attaches a static handler for favicon.ico if the root doesn't already have a handler for it without even looking at the config. If the config has a section for /favicon.ico, but the file doesn't exist, _refreshing_ the browser will throw and error in the errorlog with something like this:

\`\`\`
[17/Jan/2010:01:30:00] HTTP Traceback (most recent call last):
  File \\"/Users/wyuenho/Documents/spiralup/spiralup/lib/python2.5/site-packages/CherryPy-3.1.2-py2.5.egg/cherrypy/_cprequest.py\\", line 606, in respond
    cherrypy.response.body = self.handler()
  File \\"/Users/wyuenho/Documents/spiralup/spiralup/lib/python2.5/site-packages/CherryPy-3.1.2-py2.5.egg/cherrypy/_cpdispatch.py\\", line 25, in __call__
    return self.callable(*self.args, **self.kwargs)
  File \\"/Users/wyuenho/Documents/spiralup/spiralup/lib/python2.5/site-packages/CherryPy-3.1.2-py2.5.egg/cherrypy/_cptools.py\\", line 150, in handle_func
    handled = self.callable(*args, **self._merged_args(kwargs))
TypeError: staticfile() got multiple values for keyword argument 'filename'
\`\`\`

This obviously doesn't even tell me what values it got, so the error message doesn't even help. I'm not sure how to patch this because you need to obviously look at all the different kinds of dispatchers for the \\"/favicon.ico\\" key besides the default tree dispatcher, and I'm not familiar with all of them.

Reported by wyuenho@gmail.com

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/983
",
    "closed_at": null,
    "comments": 6,
    "comments_url": "https://api.github.com/repos/cherrypy/cherrypy/issues/983/comments",
    "created_at": "2010-01-17T06:47:16Z",
    "events_url": "https://api.github.com/repos/cherrypy/cherrypy/issues/983/events",
    "html_url": "https://github.com/cherrypy/cherrypy/issues/983",
    "id": "152024778",
    "labels": Array [
      Object {
        "color": "ee0701",
        "default": true,
        "id": 366608106,
        "name": "bug",
        "url": "https://api.github.com/repos/cherrypy/cherrypy/labels/bug",
      },
      Object {
        "color": "ededed",
        "default": false,
        "id": 366608297,
        "name": "CherryPy code",
        "url": "https://api.github.com/repos/cherrypy/cherrypy/labels/CherryPy%20code",
      },
      Object {
        "color": "128A0C",
        "default": true,
        "id": 366608109,
        "name": "help wanted",
        "url": "https://api.github.com/repos/cherrypy/cherrypy/labels/help%20wanted",
      },
      Object {
        "color": "ededed",
        "default": false,
        "id": 366608295,
        "name": "major",
        "url": "https://api.github.com/repos/cherrypy/cherrypy/labels/major",
      },
    ],
    "labels_url": "https://api.github.com/repos/cherrypy/cherrypy/issues/983/labels{/name}",
    "locked": false,
    "milestone": null,
    "number": 983,
    "repository_url": "https://api.github.com/repos/cherrypy/cherrypy",
    "score": 0.29482016,
    "state": "open",
    "title": "serving non-existent favicon.ico with staticfile throws error on refresh",
    "updated_at": "2017-02-03T16:56:35Z",
    "url": "https://api.github.com/repos/cherrypy/cherrypy/issues/983",
    "user": Object {
      "avatar_url": "https://avatars1.githubusercontent.com/u/18138808?v=3",
      "events_url": "https://api.github.com/users/bb-migration/events{/privacy}",
      "followers_url": "https://api.github.com/users/bb-migration/followers",
      "following_url": "https://api.github.com/users/bb-migration/following{/other_user}",
      "gists_url": "https://api.github.com/users/bb-migration/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/bb-migration",
      "id": 18138808,
      "login": "bb-migration",
      "organizations_url": "https://api.github.com/users/bb-migration/orgs",
      "received_events_url": "https://api.github.com/users/bb-migration/received_events",
      "repos_url": "https://api.github.com/users/bb-migration/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/bb-migration/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/bb-migration/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/bb-migration",
    },
  },
  Object {
    "assignee": null,
    "assignees": Array [],
    "body": "**Reported by aleksey_s on 2009-12-17 16:39**
Sometimes, NVDA is too verbose in console windows.
STR:
- open cmd
- run python interpreter
- type: print \\"hi\\"
  Currently, NVDA says
  h
  i
  hi
  It starts reading by letter and only then reads the entire message. This behaviour also exists in other console apps.
  **Blocked by #5027**
  **Blocking #2977, #4127, #5328**
",
    "closed_at": null,
    "comments": 12,
    "comments_url": "https://api.github.com/repos/nvaccess/nvda/issues/513/comments",
    "created_at": "2010-01-01T00:00:00Z",
    "events_url": "https://api.github.com/repos/nvaccess/nvda/issues/513/events",
    "html_url": "https://github.com/nvaccess/nvda/issues/513",
    "id": "116022543",
    "labels": Array [
      Object {
        "color": "fc2929",
        "default": true,
        "id": 284590813,
        "name": "bug",
        "url": "https://api.github.com/repos/nvaccess/nvda/labels/bug",
      },
      Object {
        "color": "5319e7",
        "default": false,
        "id": 401238340,
        "name": "p2",
        "url": "https://api.github.com/repos/nvaccess/nvda/labels/p2",
      },
      Object {
        "color": "ffffff",
        "default": false,
        "id": 284596914,
        "name": "Windows command console",
        "url": "https://api.github.com/repos/nvaccess/nvda/labels/Windows%20command%20console",
      },
    ],
    "labels_url": "https://api.github.com/repos/nvaccess/nvda/issues/513/labels{/name}",
    "locked": false,
    "milestone": null,
    "number": 513,
    "repository_url": "https://api.github.com/repos/nvaccess/nvda",
    "score": 0.5586072,
    "state": "open",
    "title": "Some output in command consoels spelled with speak typed characters enabled",
    "updated_at": "2016-07-06T00:25:51Z",
    "url": "https://api.github.com/repos/nvaccess/nvda/issues/513",
    "user": Object {
      "avatar_url": "https://avatars1.githubusercontent.com/u/14253915?v=3",
      "events_url": "https://api.github.com/users/nvaccessAuto/events{/privacy}",
      "followers_url": "https://api.github.com/users/nvaccessAuto/followers",
      "following_url": "https://api.github.com/users/nvaccessAuto/following{/other_user}",
      "gists_url": "https://api.github.com/users/nvaccessAuto/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/nvaccessAuto",
      "id": 14253915,
      "login": "nvaccessAuto",
      "organizations_url": "https://api.github.com/users/nvaccessAuto/orgs",
      "received_events_url": "https://api.github.com/users/nvaccessAuto/received_events",
      "repos_url": "https://api.github.com/users/nvaccessAuto/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/nvaccessAuto/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/nvaccessAuto/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/nvaccessAuto",
    },
  },
  Object {
    "assignee": null,
    "assignees": Array [],
    "body": "bc.. I don't have a macosx, but when I was presenting at SciPy2007, I borrowed a
Mac OS X laptop and sympy was working well (with python2.5), except plotting:

Plot(x*y)

worked fine, then I did:

Plot(sin(x)*cos(y))

and the plotting window stopped responding (the \\"hour\\" cursor when moved
over it with mouse). I think it happened always when I called Plot for the
second time.

It would be nice, if someone with macosx could verify that && fix that.

p. Original issue for \\"#3408\\":https://github.com/sympy/sympy/issues/3408: \\"http://code.google.com/p/sympy/issues/detail?id=309\\":http://code.google.com/p/sympy/issues/detail?id=309

p. Original author: \\"https://code.google.com/u/104039945248245758823/\\":https://code.google.com/u/104039945248245758823/

p. Original owner: \\"https://code.google.com/u/115549613129666820104/\\":https://code.google.com/u/115549613129666820104/
",
    "closed_at": null,
    "comments": 17,
    "comments_url": "https://api.github.com/repos/sympy/sympy/issues/3408/comments",
    "created_at": "2007-08-20T05:37:18Z",
    "events_url": "https://api.github.com/repos/sympy/sympy/issues/3408/events",
    "html_url": "https://github.com/sympy/sympy/issues/3408",
    "id": "28948494",
    "labels": Array [
      Object {
        "color": "ededed",
        "default": true,
        "id": 84627344,
        "name": "bug",
        "url": "https://api.github.com/repos/sympy/sympy/labels/bug",
      },
      Object {
        "color": "ededed",
        "default": false,
        "id": 84627341,
        "name": "imported",
        "url": "https://api.github.com/repos/sympy/sympy/labels/imported",
      },
      Object {
        "color": "0000FF",
        "default": false,
        "id": 84627346,
        "name": "plotting",
        "url": "https://api.github.com/repos/sympy/sympy/labels/plotting",
      },
      Object {
        "color": "d4c5f9",
        "default": false,
        "id": 84627345,
        "name": "valid",
        "url": "https://api.github.com/repos/sympy/sympy/labels/valid",
      },
    ],
    "labels_url": "https://api.github.com/repos/sympy/sympy/issues/3408/labels{/name}",
    "locked": false,
    "milestone": null,
    "number": 3408,
    "repository_url": "https://api.github.com/repos/sympy/sympy",
    "score": 0.14507581,
    "state": "open",
    "title": "plotting on macos x freezes",
    "updated_at": "2016-03-07T03:34:54Z",
    "url": "https://api.github.com/repos/sympy/sympy/issues/3408",
    "user": Object {
      "avatar_url": "https://avatars0.githubusercontent.com/u/20568?v=3",
      "events_url": "https://api.github.com/users/certik/events{/privacy}",
      "followers_url": "https://api.github.com/users/certik/followers",
      "following_url": "https://api.github.com/users/certik/following{/other_user}",
      "gists_url": "https://api.github.com/users/certik/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/certik",
      "id": 20568,
      "login": "certik",
      "organizations_url": "https://api.github.com/users/certik/orgs",
      "received_events_url": "https://api.github.com/users/certik/received_events",
      "repos_url": "https://api.github.com/users/certik/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/certik/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/certik/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/certik",
    },
  },
  Object {
    "assignee": null,
    "assignees": Array [],
    "body": "\`\`\`
See this thread for more info: http://groups.google.com/group/sympy/browse_thread/thread/de26d886c983fbec
\`\`\`

Original issue for #4563: http://code.google.com/p/sympy/issues/detail?id=1464
Original author: https://code.google.com/u/104039945248245758823/
",
    "closed_at": null,
    "comments": 7,
    "comments_url": "https://api.github.com/repos/sympy/sympy/issues/4563/comments",
    "created_at": "2009-06-09T06:06:53Z",
    "events_url": "https://api.github.com/repos/sympy/sympy/issues/4563/events",
    "html_url": "https://github.com/sympy/sympy/issues/4563",
    "id": "28949846",
    "labels": Array [
      Object {
        "color": "ededed",
        "default": true,
        "id": 84627344,
        "name": "bug",
        "url": "https://api.github.com/repos/sympy/sympy/labels/bug",
      },
      Object {
        "color": "c7def8",
        "default": false,
        "id": 75863299,
        "name": "Documentation",
        "url": "https://api.github.com/repos/sympy/sympy/labels/Documentation",
      },
      Object {
        "color": "009800",
        "default": false,
        "id": 75782144,
        "name": "Easy to Fix",
        "url": "https://api.github.com/repos/sympy/sympy/labels/Easy%20to%20Fix",
      },
      Object {
        "color": "ededed",
        "default": false,
        "id": 84627341,
        "name": "imported",
        "url": "https://api.github.com/repos/sympy/sympy/labels/imported",
      },
      Object {
        "color": "d4c5f9",
        "default": false,
        "id": 84627345,
        "name": "valid",
        "url": "https://api.github.com/repos/sympy/sympy/labels/valid",
      },
    ],
    "labels_url": "https://api.github.com/repos/sympy/sympy/issues/4563/labels{/name}",
    "locked": false,
    "milestone": null,
    "number": 4563,
    "repository_url": "https://api.github.com/repos/sympy/sympy",
    "score": 3.9501157,
    "state": "open",
    "title": "docs: adding instructions how to get stuff working on windows",
    "updated_at": "2016-02-25T19:02:17Z",
    "url": "https://api.github.com/repos/sympy/sympy/issues/4563",
    "user": Object {
      "avatar_url": "https://avatars0.githubusercontent.com/u/20568?v=3",
      "events_url": "https://api.github.com/users/certik/events{/privacy}",
      "followers_url": "https://api.github.com/users/certik/followers",
      "following_url": "https://api.github.com/users/certik/following{/other_user}",
      "gists_url": "https://api.github.com/users/certik/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/certik",
      "id": 20568,
      "login": "certik",
      "organizations_url": "https://api.github.com/users/certik/orgs",
      "received_events_url": "https://api.github.com/users/certik/received_events",
      "repos_url": "https://api.github.com/users/certik/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/certik/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/certik/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/certik",
    },
  },
  Object {
    "assignee": null,
    "assignees": Array [],
    "body": "**Reported by Agent Golder on 2010-03-25 10:14**
I just noticed that in some situations such as the Microsoft Office 2010 custom setup, features treeview can't be read normally but only using object navigation which sometimes is difficult to perform actions.
While of course, with Jaws anything gose normally.
Why is this? Can a fix be made?
",
    "closed_at": null,
    "comments": 4,
    "comments_url": "https://api.github.com/repos/nvaccess/nvda/issues/606/comments",
    "created_at": "2010-03-25T10:14:26Z",
    "events_url": "https://api.github.com/repos/nvaccess/nvda/issues/606/events",
    "html_url": "https://github.com/nvaccess/nvda/issues/606",
    "id": "116022897",
    "labels": Array [
      Object {
        "color": "fc2929",
        "default": true,
        "id": 284590813,
        "name": "bug",
        "url": "https://api.github.com/repos/nvaccess/nvda/labels/bug",
      },
    ],
    "labels_url": "https://api.github.com/repos/nvaccess/nvda/issues/606/labels{/name}",
    "locked": false,
    "milestone": null,
    "number": 606,
    "repository_url": "https://api.github.com/repos/nvaccess/nvda",
    "score": 0.28862232,
    "state": "open",
    "title": "Inaccessible features treeview in Microsoft Office 2010 custom setup",
    "updated_at": "2015-11-10T04:22:01Z",
    "url": "https://api.github.com/repos/nvaccess/nvda/issues/606",
    "user": Object {
      "avatar_url": "https://avatars1.githubusercontent.com/u/14253915?v=3",
      "events_url": "https://api.github.com/users/nvaccessAuto/events{/privacy}",
      "followers_url": "https://api.github.com/users/nvaccessAuto/followers",
      "following_url": "https://api.github.com/users/nvaccessAuto/following{/other_user}",
      "gists_url": "https://api.github.com/users/nvaccessAuto/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/nvaccessAuto",
      "id": 14253915,
      "login": "nvaccessAuto",
      "organizations_url": "https://api.github.com/users/nvaccessAuto/orgs",
      "received_events_url": "https://api.github.com/users/nvaccessAuto/received_events",
      "repos_url": "https://api.github.com/users/nvaccessAuto/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/nvaccessAuto/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/nvaccessAuto/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/nvaccessAuto",
    },
  },
  Object {
    "assignee": null,
    "assignees": Array [],
    "body": "**Reported by aleksey_s on 2010-02-16 05:40**
I noticed, that NVDA sometimes stops speaking of typed characters. It happens every time after resuming from standby mode and sometimes without any reason. Restarting of NVDA helps resolve this one. I think this was introduced in Sunday commits.
",
    "closed_at": null,
    "comments": 18,
    "comments_url": "https://api.github.com/repos/nvaccess/nvda/issues/562/comments",
    "created_at": "2010-02-16T05:40:42Z",
    "events_url": "https://api.github.com/repos/nvaccess/nvda/issues/562/events",
    "html_url": "https://github.com/nvaccess/nvda/issues/562",
    "id": "116022735",
    "labels": Array [
      Object {
        "color": "fc2929",
        "default": true,
        "id": 284590813,
        "name": "bug",
        "url": "https://api.github.com/repos/nvaccess/nvda/labels/bug",
      },
    ],
    "labels_url": "https://api.github.com/repos/nvaccess/nvda/issues/562/labels{/name}",
    "locked": false,
    "milestone": null,
    "number": 562,
    "repository_url": "https://api.github.com/repos/nvaccess/nvda",
    "score": 0.37493137,
    "state": "open",
    "title": "NVDA stops speaking of typed characters from time to time",
    "updated_at": "2015-11-10T04:20:24Z",
    "url": "https://api.github.com/repos/nvaccess/nvda/issues/562",
    "user": Object {
      "avatar_url": "https://avatars1.githubusercontent.com/u/14253915?v=3",
      "events_url": "https://api.github.com/users/nvaccessAuto/events{/privacy}",
      "followers_url": "https://api.github.com/users/nvaccessAuto/followers",
      "following_url": "https://api.github.com/users/nvaccessAuto/following{/other_user}",
      "gists_url": "https://api.github.com/users/nvaccessAuto/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/nvaccessAuto",
      "id": 14253915,
      "login": "nvaccessAuto",
      "organizations_url": "https://api.github.com/users/nvaccessAuto/orgs",
      "received_events_url": "https://api.github.com/users/nvaccessAuto/received_events",
      "repos_url": "https://api.github.com/users/nvaccessAuto/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/nvaccessAuto/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/nvaccessAuto/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/nvaccessAuto",
    },
  },
  Object {
    "assignee": null,
    "assignees": Array [],
    "body": "**Reported by aleksey_s on 2010-02-13 08:34**
## steps to reproduce
- ensure you have more than one keyboard layout installed
- start->run->cmd
- type something and try to change layout
- ensure you are entering letters in newly set language
  ## current results

NVDA doesn't report the change to keyboard layout
## expected results

NVDA must gracefully report the change
",
    "closed_at": null,
    "comments": 2,
    "comments_url": "https://api.github.com/repos/nvaccess/nvda/issues/556/comments",
    "created_at": "2010-02-13T08:34:34Z",
    "events_url": "https://api.github.com/repos/nvaccess/nvda/issues/556/events",
    "html_url": "https://github.com/nvaccess/nvda/issues/556",
    "id": "116022712",
    "labels": Array [
      Object {
        "color": "fc2929",
        "default": true,
        "id": 284590813,
        "name": "bug",
        "url": "https://api.github.com/repos/nvaccess/nvda/labels/bug",
      },
      Object {
        "color": "ffffff",
        "default": false,
        "id": 284596914,
        "name": "Windows command console",
        "url": "https://api.github.com/repos/nvaccess/nvda/labels/Windows%20command%20console",
      },
    ],
    "labels_url": "https://api.github.com/repos/nvaccess/nvda/issues/556/labels{/name}",
    "locked": false,
    "milestone": null,
    "number": 556,
    "repository_url": "https://api.github.com/repos/nvaccess/nvda",
    "score": 3.9446173,
    "state": "open",
    "title": "Keyboard layout change is not reported in console windows",
    "updated_at": "2015-11-10T04:20:11Z",
    "url": "https://api.github.com/repos/nvaccess/nvda/issues/556",
    "user": Object {
      "avatar_url": "https://avatars1.githubusercontent.com/u/14253915?v=3",
      "events_url": "https://api.github.com/users/nvaccessAuto/events{/privacy}",
      "followers_url": "https://api.github.com/users/nvaccessAuto/followers",
      "following_url": "https://api.github.com/users/nvaccessAuto/following{/other_user}",
      "gists_url": "https://api.github.com/users/nvaccessAuto/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/nvaccessAuto",
      "id": 14253915,
      "login": "nvaccessAuto",
      "organizations_url": "https://api.github.com/users/nvaccessAuto/orgs",
      "received_events_url": "https://api.github.com/users/nvaccessAuto/received_events",
      "repos_url": "https://api.github.com/users/nvaccessAuto/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/nvaccessAuto/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/nvaccessAuto/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/nvaccessAuto",
    },
  },
  Object {
    "assignee": null,
    "assignees": Array [],
    "body": "**Reported by janusz on 2010-01-18 20:45**
The algorithms, which are responsible for getting text information from The dialog Window, which can be accessed by recalling ffdshow  audio decoder. When user is triing to activate this dialog window, NVDA can freeze or user must wait more than 7 seconds until NVDA is ready for interactioning with user. This issue is also presented, if user is triing to use INSERT and 4 or 6 key, which is awailable on The numeric key pad. The Klitecodecpack, where The ffdshow filter is awailable can be downloaded by using The following direct link. 

ftp.tw.xemacs.org/cpatch/media/k-lite/klcodec561f.exe

The package download syze is 14,7 MB. It is necessary to install this package, please let installer to chose The default settings. To spend Yours work and to free Your time from downloading and using compatible multimedia player, You can activate The dialog Window by exactly running The following command. I love procedures direct calls from dynamic linked libraries by using rundll32.exe command. It is a little pleasure for programmers.

C:\\\\WINDOWS\\\\system32\\\\rundll32.exe ffdshow.ax,configureAudio

This command will not run if You will not execute it from The  

\\\\Program Files\\\\K-Lite Codec Pack\\\\ffdshow

The installation program for Klite codecpack will create necessary links for activating some configuration options without need to run compatible multimedia player. Please explore The Programs folder detaily and You will find out, which special links have been created. Please, try to fix this issue. Many visually impaired users would be very deeply appreciating The programmer, who would create new application setting file specifically for all dialog windows, which are awailable for managing all codecs and filters. The purpose of this new application settings file is to force NVDA to get The labels of all editable fields and other important user interface controls. Because The source code of those dlls is frelly awailable, it is very nice C programming language complex source code, somebody would get those labels by analysing all source code or somebody would try to get in touch with The core developers of The Klitecodecpacks and all dlls. This codecs is ammazing, visually impaired user can modifi The sound while plaing multimedia content without need to load The multimedia file to The sound editor. The dolby filter and other modules are working reliably. Be very careful while exploring and experimenting with all numbers for modifiing The equalizer. IN some relationships between various settings, Your computer would freeze and You would have to be forced to turned it of force. 
",
    "closed_at": null,
    "comments": 1,
    "comments_url": "https://api.github.com/repos/nvaccess/nvda/issues/533/comments",
    "created_at": "2010-01-18T20:45:39Z",
    "events_url": "https://api.github.com/repos/nvaccess/nvda/issues/533/events",
    "html_url": "https://github.com/nvaccess/nvda/issues/533",
    "id": "116022614",
    "labels": Array [
      Object {
        "color": "fc2929",
        "default": true,
        "id": 284590813,
        "name": "bug",
        "url": "https://api.github.com/repos/nvaccess/nvda/labels/bug",
      },
    ],
    "labels_url": "https://api.github.com/repos/nvaccess/nvda/issues/533/labels{/name}",
    "locked": false,
    "milestone": null,
    "number": 533,
    "repository_url": "https://api.github.com/repos/nvaccess/nvda",
    "score": 0.28811592,
    "state": "open",
    "title": "NVDA is freezing while activating The dialog window which is awailable in The ffdshow audio decoder. This issue can cause that Nvda can not be used. Or NVDA can respond after 8 or more seconds. The algorithms, which are responsible for getting The text from The dialog Window are very complex and are allocating many system resources until The text from this dialog box is ready for speech synthesizer or Brltty.",
    "updated_at": "2015-11-10T04:19:17Z",
    "url": "https://api.github.com/repos/nvaccess/nvda/issues/533",
    "user": Object {
      "avatar_url": "https://avatars1.githubusercontent.com/u/14253915?v=3",
      "events_url": "https://api.github.com/users/nvaccessAuto/events{/privacy}",
      "followers_url": "https://api.github.com/users/nvaccessAuto/followers",
      "following_url": "https://api.github.com/users/nvaccessAuto/following{/other_user}",
      "gists_url": "https://api.github.com/users/nvaccessAuto/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/nvaccessAuto",
      "id": 14253915,
      "login": "nvaccessAuto",
      "organizations_url": "https://api.github.com/users/nvaccessAuto/orgs",
      "received_events_url": "https://api.github.com/users/nvaccessAuto/received_events",
      "repos_url": "https://api.github.com/users/nvaccessAuto/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/nvaccessAuto/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/nvaccessAuto/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/nvaccessAuto",
    },
  },
  Object {
    "assignee": null,
    "assignees": Array [],
    "body": "**Reported by Hari on 2009-12-15 15:11**
When deleting a selected text in any word pad/text editor, the NVDA, version 2009.1 (most recent release), says: \\"unselecting\\" followed by announcement of a word if present -- and if not, announcement of a carriage return. E.g., let's say we have following words written: \\"my test\\". And let's say we deleted the word \\"my\\", the NVDA says \\"unselecting test\\", which, you could see, is quite confusing. Now let's say the text is followed by a carriage return, it say the following: \\"unselecting carriage return\\". As noted before, this issue is global, i.e. it occurs in MS Word, Windows Word Pad, Jarte text editor, and so forth. 
",
    "closed_at": null,
    "comments": 4,
    "comments_url": "https://api.github.com/repos/nvaccess/nvda/issues/510/comments",
    "created_at": "2010-01-01T00:00:00Z",
    "events_url": "https://api.github.com/repos/nvaccess/nvda/issues/510/events",
    "html_url": "https://github.com/nvaccess/nvda/issues/510",
    "id": "116022534",
    "labels": Array [
      Object {
        "color": "fc2929",
        "default": true,
        "id": 284590813,
        "name": "bug",
        "url": "https://api.github.com/repos/nvaccess/nvda/labels/bug",
      },
    ],
    "labels_url": "https://api.github.com/repos/nvaccess/nvda/issues/510/labels{/name}",
    "locked": false,
    "milestone": null,
    "number": 510,
    "repository_url": "https://api.github.com/repos/nvaccess/nvda",
    "score": 0.3571519,
    "state": "open",
    "title": "Unclear indication of text deletion",
    "updated_at": "2015-11-10T04:18:22Z",
    "url": "https://api.github.com/repos/nvaccess/nvda/issues/510",
    "user": Object {
      "avatar_url": "https://avatars1.githubusercontent.com/u/14253915?v=3",
      "events_url": "https://api.github.com/users/nvaccessAuto/events{/privacy}",
      "followers_url": "https://api.github.com/users/nvaccessAuto/followers",
      "following_url": "https://api.github.com/users/nvaccessAuto/following{/other_user}",
      "gists_url": "https://api.github.com/users/nvaccessAuto/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/nvaccessAuto",
      "id": 14253915,
      "login": "nvaccessAuto",
      "organizations_url": "https://api.github.com/users/nvaccessAuto/orgs",
      "received_events_url": "https://api.github.com/users/nvaccessAuto/received_events",
      "repos_url": "https://api.github.com/users/nvaccessAuto/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/nvaccessAuto/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/nvaccessAuto/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/nvaccessAuto",
    },
  },
  Object {
    "assignee": null,
    "assignees": Array [],
    "body": "**Reported by scottbb on 2009-12-07 02:46**
When using Cdex there is no beeping for the background progress bar.
",
    "closed_at": null,
    "comments": 3,
    "comments_url": "https://api.github.com/repos/nvaccess/nvda/issues/500/comments",
    "created_at": "2010-01-01T00:00:00Z",
    "events_url": "https://api.github.com/repos/nvaccess/nvda/issues/500/events",
    "html_url": "https://github.com/nvaccess/nvda/issues/500",
    "id": "116022500",
    "labels": Array [
      Object {
        "color": "fc2929",
        "default": true,
        "id": 284590813,
        "name": "bug",
        "url": "https://api.github.com/repos/nvaccess/nvda/labels/bug",
      },
    ],
    "labels_url": "https://api.github.com/repos/nvaccess/nvda/issues/500/labels{/name}",
    "locked": false,
    "milestone": null,
    "number": 500,
    "repository_url": "https://api.github.com/repos/nvaccess/nvda",
    "score": 0.2525445,
    "state": "open",
    "title": "Cdex is not beeping in background or foreground  progress bars",
    "updated_at": "2015-11-10T04:18:00Z",
    "url": "https://api.github.com/repos/nvaccess/nvda/issues/500",
    "user": Object {
      "avatar_url": "https://avatars1.githubusercontent.com/u/14253915?v=3",
      "events_url": "https://api.github.com/users/nvaccessAuto/events{/privacy}",
      "followers_url": "https://api.github.com/users/nvaccessAuto/followers",
      "following_url": "https://api.github.com/users/nvaccessAuto/following{/other_user}",
      "gists_url": "https://api.github.com/users/nvaccessAuto/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/nvaccessAuto",
      "id": 14253915,
      "login": "nvaccessAuto",
      "organizations_url": "https://api.github.com/users/nvaccessAuto/orgs",
      "received_events_url": "https://api.github.com/users/nvaccessAuto/received_events",
      "repos_url": "https://api.github.com/users/nvaccessAuto/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/nvaccessAuto/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/nvaccessAuto/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/nvaccessAuto",
    },
  },
  Object {
    "assignee": null,
    "assignees": Array [],
    "body": "**Reported by pvagner on 2009-10-29 19:14**
STR:
1) Open your outlook express and focus the list of messages.
2) Make sure focus is set to the item immediately before the last item in the list (the second item from the very bottom).
3) Press the delete key.

Actual results:
NVDA stays silent and you need to use NVDA+tab or NVDA+up arrow to get the currently selected item spoken.

Expected results:
As the last message in the list gains the focus, NVDA should correctly announce to that fact.
",
    "closed_at": null,
    "comments": 2,
    "comments_url": "https://api.github.com/repos/nvaccess/nvda/issues/446/comments",
    "created_at": "2010-01-01T00:00:00Z",
    "events_url": "https://api.github.com/repos/nvaccess/nvda/issues/446/events",
    "html_url": "https://github.com/nvaccess/nvda/issues/446",
    "id": "116022302",
    "labels": Array [
      Object {
        "color": "fc2929",
        "default": true,
        "id": 284590813,
        "name": "bug",
        "url": "https://api.github.com/repos/nvaccess/nvda/labels/bug",
      },
    ],
    "labels_url": "https://api.github.com/repos/nvaccess/nvda/issues/446/labels{/name}",
    "locked": false,
    "milestone": null,
    "number": 446,
    "repository_url": "https://api.github.com/repos/nvaccess/nvda",
    "score": 0.5102169,
    "state": "open",
    "title": "When deleting one before the last message in the outlook express message list NVDA fails to announce new item in focus",
    "updated_at": "2015-11-10T04:16:01Z",
    "url": "https://api.github.com/repos/nvaccess/nvda/issues/446",
    "user": Object {
      "avatar_url": "https://avatars1.githubusercontent.com/u/14253915?v=3",
      "events_url": "https://api.github.com/users/nvaccessAuto/events{/privacy}",
      "followers_url": "https://api.github.com/users/nvaccessAuto/followers",
      "following_url": "https://api.github.com/users/nvaccessAuto/following{/other_user}",
      "gists_url": "https://api.github.com/users/nvaccessAuto/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/nvaccessAuto",
      "id": 14253915,
      "login": "nvaccessAuto",
      "organizations_url": "https://api.github.com/users/nvaccessAuto/orgs",
      "received_events_url": "https://api.github.com/users/nvaccessAuto/received_events",
      "repos_url": "https://api.github.com/users/nvaccessAuto/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/nvaccessAuto/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/nvaccessAuto/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/nvaccessAuto",
    },
  },
  Object {
    "assignee": null,
    "assignees": Array [],
    "body": "**Reported by aarnott on 2009-09-18 22:35**
A hidden text control is embedded on the Visual Studio (2008 and 2010 beta 1) Project Conversion dialog (opening page).  Windows Eyes can read it, but NVDA cannot.
",
    "closed_at": null,
    "comments": 0,
    "comments_url": "https://api.github.com/repos/nvaccess/nvda/issues/419/comments",
    "created_at": "2010-01-01T00:00:00Z",
    "events_url": "https://api.github.com/repos/nvaccess/nvda/issues/419/events",
    "html_url": "https://github.com/nvaccess/nvda/issues/419",
    "id": "116022216",
    "labels": Array [
      Object {
        "color": "ffffff",
        "default": false,
        "id": 284598354,
        "name": "App specific: Microsoft Visual Studio",
        "url": "https://api.github.com/repos/nvaccess/nvda/labels/App%20specific:%20Microsoft%20Visual%20Studio",
      },
      Object {
        "color": "fc2929",
        "default": true,
        "id": 284590813,
        "name": "bug",
        "url": "https://api.github.com/repos/nvaccess/nvda/labels/bug",
      },
    ],
    "labels_url": "https://api.github.com/repos/nvaccess/nvda/issues/419/labels{/name}",
    "locked": false,
    "milestone": null,
    "number": 419,
    "repository_url": "https://api.github.com/repos/nvaccess/nvda",
    "score": 0.6790957,
    "state": "open",
    "title": "Unable to read text in hidden textbox",
    "updated_at": "2015-11-10T04:14:59Z",
    "url": "https://api.github.com/repos/nvaccess/nvda/issues/419",
    "user": Object {
      "avatar_url": "https://avatars1.githubusercontent.com/u/14253915?v=3",
      "events_url": "https://api.github.com/users/nvaccessAuto/events{/privacy}",
      "followers_url": "https://api.github.com/users/nvaccessAuto/followers",
      "following_url": "https://api.github.com/users/nvaccessAuto/following{/other_user}",
      "gists_url": "https://api.github.com/users/nvaccessAuto/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/nvaccessAuto",
      "id": 14253915,
      "login": "nvaccessAuto",
      "organizations_url": "https://api.github.com/users/nvaccessAuto/orgs",
      "received_events_url": "https://api.github.com/users/nvaccessAuto/received_events",
      "repos_url": "https://api.github.com/users/nvaccessAuto/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/nvaccessAuto/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/nvaccessAuto/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/nvaccessAuto",
    },
  },
  Object {
    "assignee": null,
    "assignees": Array [],
    "body": "**Reported by jteh on 2009-08-25 03:42**
While NVDA is running, the system will not go into standby mode automatically despite being configured to do so.

Str:
1. Ensure that no other background tasks which will prevent standby are running; e.g. audio players, etc.
2. Set the system standby time to 1 minute. (In Windows XP, Control Panel -> Power Options -> Power Schemes tab -> System standby...)
3. Press NVDA+f12 and let the speech reach completion. Do not hit control to interrupt it. Otherwise, the speech will pause instead of finishing.
4. Wait a little more than 1 minute.
   Actual: The system does not go into standby mode.
   Expected: The system should go into standby mode after 1 minute.

Additional info:
This occurs because tones keeps an instance of \`nvwave.WavePlayer\` which it does not close after each tone plays. We do this so that we don't have to (synchronously) wait for the tone to finish playing. Calling \`tones.player.close()\` from the Python Console fixes this problem. Fixing this will require refactoring the tones code so that it calls \`player.idle()\` after each tone, which will probably need to be done in a background thread.
",
    "closed_at": null,
    "comments": 3,
    "comments_url": "https://api.github.com/repos/nvaccess/nvda/issues/400/comments",
    "created_at": "2010-01-01T00:00:00Z",
    "events_url": "https://api.github.com/repos/nvaccess/nvda/issues/400/events",
    "html_url": "https://github.com/nvaccess/nvda/issues/400",
    "id": "116022151",
    "labels": Array [
      Object {
        "color": "fc2929",
        "default": true,
        "id": 284590813,
        "name": "bug",
        "url": "https://api.github.com/repos/nvaccess/nvda/labels/bug",
      },
    ],
    "labels_url": "https://api.github.com/repos/nvaccess/nvda/issues/400/labels{/name}",
    "locked": false,
    "milestone": null,
    "number": 400,
    "repository_url": "https://api.github.com/repos/nvaccess/nvda",
    "score": 0.28862226,
    "state": "open",
    "title": "NVDA prevents automatic system standby",
    "updated_at": "2015-11-10T04:14:15Z",
    "url": "https://api.github.com/repos/nvaccess/nvda/issues/400",
    "user": Object {
      "avatar_url": "https://avatars1.githubusercontent.com/u/14253915?v=3",
      "events_url": "https://api.github.com/users/nvaccessAuto/events{/privacy}",
      "followers_url": "https://api.github.com/users/nvaccessAuto/followers",
      "following_url": "https://api.github.com/users/nvaccessAuto/following{/other_user}",
      "gists_url": "https://api.github.com/users/nvaccessAuto/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/nvaccessAuto",
      "id": 14253915,
      "login": "nvaccessAuto",
      "organizations_url": "https://api.github.com/users/nvaccessAuto/orgs",
      "received_events_url": "https://api.github.com/users/nvaccessAuto/received_events",
      "repos_url": "https://api.github.com/users/nvaccessAuto/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/nvaccessAuto/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/nvaccessAuto/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/nvaccessAuto",
    },
  },
  Object {
    "assignee": null,
    "assignees": Array [],
    "body": "bc.. The ultimate solution is to provide test access to all developers on our
buildbots (the buildbots allow to test only a patch that you send to them)
& setup parallel testing & provide several levels of testing (core, basic,
thorough). 

Any volunteers to setup buildbots? I'll provide you with necessary access.

I can do that after I finish my finals. http://buildbot.sympy.org/waterfall

p. Original issue for \\"#4216\\":https://github.com/sympy/sympy/issues/4216: \\"http://code.google.com/p/sympy/issues/detail?id=1117\\":http://code.google.com/p/sympy/issues/detail?id=1117

p. Original author: \\"https://code.google.com/u/104039945248245758823/\\":https://code.google.com/u/104039945248245758823/
",
    "closed_at": null,
    "comments": 39,
    "comments_url": "https://api.github.com/repos/sympy/sympy/issues/4216/comments",
    "created_at": "2008-09-21T01:05:27Z",
    "events_url": "https://api.github.com/repos/sympy/sympy/issues/4216/events",
    "html_url": "https://github.com/sympy/sympy/issues/4216",
    "id": "28949449",
    "labels": Array [
      Object {
        "color": "800080",
        "default": false,
        "id": 84627441,
        "name": "Alternate Python",
        "url": "https://api.github.com/repos/sympy/sympy/labels/Alternate%20Python",
      },
      Object {
        "color": "ededed",
        "default": true,
        "id": 84627344,
        "name": "bug",
        "url": "https://api.github.com/repos/sympy/sympy/labels/bug",
      },
      Object {
        "color": "ededed",
        "default": false,
        "id": 84627341,
        "name": "imported",
        "url": "https://api.github.com/repos/sympy/sympy/labels/imported",
      },
      Object {
        "color": "c7def8",
        "default": false,
        "id": 84627389,
        "name": "Testing",
        "url": "https://api.github.com/repos/sympy/sympy/labels/Testing",
      },
      Object {
        "color": "d4c5f9",
        "default": false,
        "id": 84627345,
        "name": "valid",
        "url": "https://api.github.com/repos/sympy/sympy/labels/valid",
      },
    ],
    "labels_url": "https://api.github.com/repos/sympy/sympy/issues/4216/labels{/name}",
    "locked": false,
    "milestone": null,
    "number": 4216,
    "repository_url": "https://api.github.com/repos/sympy/sympy",
    "score": 0.124234945,
    "state": "open",
    "title": "Setup buildbot (again)",
    "updated_at": "2015-04-17T16:59:21Z",
    "url": "https://api.github.com/repos/sympy/sympy/issues/4216",
    "user": Object {
      "avatar_url": "https://avatars0.githubusercontent.com/u/20568?v=3",
      "events_url": "https://api.github.com/users/certik/events{/privacy}",
      "followers_url": "https://api.github.com/users/certik/followers",
      "following_url": "https://api.github.com/users/certik/following{/other_user}",
      "gists_url": "https://api.github.com/users/certik/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/certik",
      "id": 20568,
      "login": "certik",
      "organizations_url": "https://api.github.com/users/certik/orgs",
      "received_events_url": "https://api.github.com/users/certik/received_events",
      "repos_url": "https://api.github.com/users/certik/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/certik/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/certik/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/certik",
    },
  },
  Object {
    "assignee": Object {
      "avatar_url": "https://avatars0.githubusercontent.com/u/20568?v=3",
      "events_url": "https://api.github.com/users/certik/events{/privacy}",
      "followers_url": "https://api.github.com/users/certik/followers",
      "following_url": "https://api.github.com/users/certik/following{/other_user}",
      "gists_url": "https://api.github.com/users/certik/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/certik",
      "id": 20568,
      "login": "certik",
      "organizations_url": "https://api.github.com/users/certik/orgs",
      "received_events_url": "https://api.github.com/users/certik/received_events",
      "repos_url": "https://api.github.com/users/certik/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/certik/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/certik/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/certik",
    },
    "assignees": Array [
      Object {
        "avatar_url": "https://avatars0.githubusercontent.com/u/20568?v=3",
        "events_url": "https://api.github.com/users/certik/events{/privacy}",
        "followers_url": "https://api.github.com/users/certik/followers",
        "following_url": "https://api.github.com/users/certik/following{/other_user}",
        "gists_url": "https://api.github.com/users/certik/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/certik",
        "id": 20568,
        "login": "certik",
        "organizations_url": "https://api.github.com/users/certik/orgs",
        "received_events_url": "https://api.github.com/users/certik/received_events",
        "repos_url": "https://api.github.com/users/certik/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/certik/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/certik/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/certik",
      },
    ],
    "body": "bc.. > Perfect. Is there something you would add to our installation instructions?

> I need to get to some windows machine and try the experience for myself.
> Just one thing. Copy isympy.py in Scripts directory along with plain
> isympy as windows can not executes files without an extension.

p. Original issue for \\"#3791\\":https://github.com/sympy/sympy/issues/3791: \\"http://code.google.com/p/sympy/issues/detail?id=692\\":http://code.google.com/p/sympy/issues/detail?id=692

p. Original author: \\"https://code.google.com/u/104039945248245758823/\\":https://code.google.com/u/104039945248245758823/

p. Original owner: \\"https://code.google.com/u/104039945248245758823/\\":https://code.google.com/u/104039945248245758823/
",
    "closed_at": null,
    "comments": 10,
    "comments_url": "https://api.github.com/repos/sympy/sympy/issues/3791/comments",
    "created_at": "2008-02-10T10:39:45Z",
    "events_url": "https://api.github.com/repos/sympy/sympy/issues/3791/events",
    "html_url": "https://github.com/sympy/sympy/issues/3791",
    "id": "28948943",
    "labels": Array [
      Object {
        "color": "ededed",
        "default": true,
        "id": 84627344,
        "name": "bug",
        "url": "https://api.github.com/repos/sympy/sympy/labels/bug",
      },
      Object {
        "color": "ededed",
        "default": false,
        "id": 84627341,
        "name": "imported",
        "url": "https://api.github.com/repos/sympy/sympy/labels/imported",
      },
      Object {
        "color": "d4c5f9",
        "default": false,
        "id": 84627345,
        "name": "valid",
        "url": "https://api.github.com/repos/sympy/sympy/labels/valid",
      },
    ],
    "labels_url": "https://api.github.com/repos/sympy/sympy/issues/3791/labels{/name}",
    "locked": false,
    "milestone": null,
    "number": 3791,
    "repository_url": "https://api.github.com/repos/sympy/sympy",
    "score": 0.572412,
    "state": "open",
    "title": "copy (not move) isympy to isympy.py",
    "updated_at": "2015-04-17T16:59:21Z",
    "url": "https://api.github.com/repos/sympy/sympy/issues/3791",
    "user": Object {
      "avatar_url": "https://avatars0.githubusercontent.com/u/20568?v=3",
      "events_url": "https://api.github.com/users/certik/events{/privacy}",
      "followers_url": "https://api.github.com/users/certik/followers",
      "following_url": "https://api.github.com/users/certik/following{/other_user}",
      "gists_url": "https://api.github.com/users/certik/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/certik",
      "id": 20568,
      "login": "certik",
      "organizations_url": "https://api.github.com/users/certik/orgs",
      "received_events_url": "https://api.github.com/users/certik/received_events",
      "repos_url": "https://api.github.com/users/certik/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/certik/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/certik/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/certik",
    },
  },
  Object {
    "assignee": Object {
      "avatar_url": "https://avatars0.githubusercontent.com/u/71486?v=3",
      "events_url": "https://api.github.com/users/asmeurer/events{/privacy}",
      "followers_url": "https://api.github.com/users/asmeurer/followers",
      "following_url": "https://api.github.com/users/asmeurer/following{/other_user}",
      "gists_url": "https://api.github.com/users/asmeurer/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/asmeurer",
      "id": 71486,
      "login": "asmeurer",
      "organizations_url": "https://api.github.com/users/asmeurer/orgs",
      "received_events_url": "https://api.github.com/users/asmeurer/received_events",
      "repos_url": "https://api.github.com/users/asmeurer/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/asmeurer/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/asmeurer/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/asmeurer",
    },
    "assignees": Array [
      Object {
        "avatar_url": "https://avatars0.githubusercontent.com/u/71486?v=3",
        "events_url": "https://api.github.com/users/asmeurer/events{/privacy}",
        "followers_url": "https://api.github.com/users/asmeurer/followers",
        "following_url": "https://api.github.com/users/asmeurer/following{/other_user}",
        "gists_url": "https://api.github.com/users/asmeurer/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/asmeurer",
        "id": 71486,
        "login": "asmeurer",
        "organizations_url": "https://api.github.com/users/asmeurer/orgs",
        "received_events_url": "https://api.github.com/users/asmeurer/received_events",
        "repos_url": "https://api.github.com/users/asmeurer/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/asmeurer/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/asmeurer/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/asmeurer",
      },
    ],
    "body": "\`\`\`
Whenever I run the test suite on my Mac OS X 10.6 machine, as soon as I get to the plotting tests, 
the Python rocket ship application (the one in 
/Library/Frameworks/Python.framework/Versions/2.6/Resources/Python.app in the default Mac OS 
X install) starts bouncing in the Dock, and keeps bouncing until the tests complete, at which point it 
quits.  No windows ever open, but it is really annoying nonetheless because it steals the keyboard 
focus whenever it happens, and if the tests run for long enough and the computer is idle, it causes 
the \\"beachball of death\\" to start spinning until you click on something else.  

Use of the -k option reveals that this happens with any test in test_plotting.py, though the program 
launches only once per test run.  

Do any Linux or Windows users have this problem?  I can see why it is happening, because plots 
open in that same rocket ship application, but it is really annoying and if it could somehow not be 
opened or opened in the background, it would be great.
\`\`\`

Original issue for #4966: http://code.google.com/p/sympy/issues/detail?id=1867
Original author: https://code.google.com/u/asmeurer@gmail.com/
Referenced issues: #5243
Original owner: https://code.google.com/u/asmeurer@gmail.com/
",
    "closed_at": null,
    "comments": 6,
    "comments_url": "https://api.github.com/repos/sympy/sympy/issues/4966/comments",
    "created_at": "2010-03-20T16:09:09Z",
    "events_url": "https://api.github.com/repos/sympy/sympy/issues/4966/events",
    "html_url": "https://github.com/sympy/sympy/issues/4966",
    "id": "28950379",
    "labels": Array [
      Object {
        "color": "ededed",
        "default": true,
        "id": 84627344,
        "name": "bug",
        "url": "https://api.github.com/repos/sympy/sympy/labels/bug",
      },
      Object {
        "color": "ededed",
        "default": false,
        "id": 84627341,
        "name": "imported",
        "url": "https://api.github.com/repos/sympy/sympy/labels/imported",
      },
      Object {
        "color": "0000FF",
        "default": false,
        "id": 84627346,
        "name": "plotting",
        "url": "https://api.github.com/repos/sympy/sympy/labels/plotting",
      },
      Object {
        "color": "c7def8",
        "default": false,
        "id": 84627389,
        "name": "Testing",
        "url": "https://api.github.com/repos/sympy/sympy/labels/Testing",
      },
      Object {
        "color": "d4c5f9",
        "default": false,
        "id": 84627345,
        "name": "valid",
        "url": "https://api.github.com/repos/sympy/sympy/labels/valid",
      },
    ],
    "labels_url": "https://api.github.com/repos/sympy/sympy/issues/4966/labels{/name}",
    "locked": false,
    "milestone": null,
    "number": 4966,
    "repository_url": "https://api.github.com/repos/sympy/sympy",
    "score": 0.381608,
    "state": "open",
    "title": "plotting tests open Python rocket ship application in Mac OS X",
    "updated_at": "2015-04-17T16:58:12Z",
    "url": "https://api.github.com/repos/sympy/sympy/issues/4966",
    "user": Object {
      "avatar_url": "https://avatars0.githubusercontent.com/u/71486?v=3",
      "events_url": "https://api.github.com/users/asmeurer/events{/privacy}",
      "followers_url": "https://api.github.com/users/asmeurer/followers",
      "following_url": "https://api.github.com/users/asmeurer/following{/other_user}",
      "gists_url": "https://api.github.com/users/asmeurer/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/asmeurer",
      "id": 71486,
      "login": "asmeurer",
      "organizations_url": "https://api.github.com/users/asmeurer/orgs",
      "received_events_url": "https://api.github.com/users/asmeurer/received_events",
      "repos_url": "https://api.github.com/users/asmeurer/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/asmeurer/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/asmeurer/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/asmeurer",
    },
  },
  Object {
    "assignee": null,
    "assignees": Array [],
    "body": "bc.. V 6.5
the following code Crash:
- cannot do a correct loop to display 1000 circle : why catch an exception ?
  -the labels of the second plot \\"p2\\" are not correcly displayed 

Warning: creating lambda evaluator failed. Falling back on sympy subs
evaluator.
Warning: creating lambda evaluator failed. Falling back on sympy subs
evaluator.
Uncaught exception in event loop: valeur non valide

from sympy.geometry.point import Point
from sympy.geometry.ellipse import Circle
from sympy import *

p = Plot(axes='label_axes=True', visible=False)

for i in range (10):
  try:
      c=  Circle(Point(0,0), i)
      p[i] = c
  except Exception, err:
      print str(err)

p.show()

p2 = Plot(axes='label_axes=True')

c = Circle(Point(0,0), 1)
t = c.tangent_line(c.random_point())
p2[0] = c
p2[1] = t

p. Original issue for \\"#4446\\":https://github.com/sympy/sympy/issues/4446: \\"http://code.google.com/p/sympy/issues/detail?id=1347\\":http://code.google.com/p/sympy/issues/detail?id=1347

p. Original author: \\"https://code.google.com/u/102679851029648305776/\\":https://code.google.com/u/102679851029648305776/
",
    "closed_at": null,
    "comments": 4,
    "comments_url": "https://api.github.com/repos/sympy/sympy/issues/4446/comments",
    "created_at": "2009-03-25T20:57:24Z",
    "events_url": "https://api.github.com/repos/sympy/sympy/issues/4446/events",
    "html_url": "https://github.com/sympy/sympy/issues/4446",
    "id": "28949709",
    "labels": Array [
      Object {
        "color": "ededed",
        "default": true,
        "id": 84627344,
        "name": "bug",
        "url": "https://api.github.com/repos/sympy/sympy/labels/bug",
      },
      Object {
        "color": "ededed",
        "default": false,
        "id": 84627341,
        "name": "imported",
        "url": "https://api.github.com/repos/sympy/sympy/labels/imported",
      },
      Object {
        "color": "d4c5f9",
        "default": false,
        "id": 84627345,
        "name": "valid",
        "url": "https://api.github.com/repos/sympy/sympy/labels/valid",
      },
    ],
    "labels_url": "https://api.github.com/repos/sympy/sympy/issues/4446/labels{/name}",
    "locked": false,
    "milestone": null,
    "number": 4446,
    "repository_url": "https://api.github.com/repos/sympy/sympy",
    "score": 0.40574965,
    "state": "open",
    "title": "creating lambda evaluator failed",
    "updated_at": "2015-04-17T16:58:12Z",
    "url": "https://api.github.com/repos/sympy/sympy/issues/4446",
    "user": Object {
      "avatar_url": "https://avatars3.githubusercontent.com/u/6188475?v=3",
      "events_url": "https://api.github.com/users/sympy-issue-migrator/events{/privacy}",
      "followers_url": "https://api.github.com/users/sympy-issue-migrator/followers",
      "following_url": "https://api.github.com/users/sympy-issue-migrator/following{/other_user}",
      "gists_url": "https://api.github.com/users/sympy-issue-migrator/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/sympy-issue-migrator",
      "id": 6188475,
      "login": "sympy-issue-migrator",
      "organizations_url": "https://api.github.com/users/sympy-issue-migrator/orgs",
      "received_events_url": "https://api.github.com/users/sympy-issue-migrator/received_events",
      "repos_url": "https://api.github.com/users/sympy-issue-migrator/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/sympy-issue-migrator/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/sympy-issue-migrator/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/sympy-issue-migrator",
    },
  },
  Object {
    "assignee": null,
    "assignees": Array [],
    "body": "\`\`\`
I am using sympy 0.6.5 on linux but I see the behavior on windows too.

In [10]: sympy.sympify('A>2')
Out[10]: 2 < A

In [11]: sympy.sympify('A==2')
Out[11]: False


I even tried using the verbose \\"Equality\\" function:

This works and returns an expression that prints a \\"A == 2\\"
In [16]: sympy.sympify('Equality(A,2)')
Out[16]: A == 2

But \\"A == 2\\" will not sympify
In [17]: sympy.sympify('A == 2')
Out[17]: False

Using Equality() is very verbose so I was hoping that it was possible to 
get == working.

--Tom
\`\`\`

Original issue for #4724: http://code.google.com/p/sympy/issues/detail?id=1625
Original author: https://code.google.com/u/110078974596186779257/
",
    "closed_at": null,
    "comments": 10,
    "comments_url": "https://api.github.com/repos/sympy/sympy/issues/4724/comments",
    "created_at": "2009-09-01T04:11:45Z",
    "events_url": "https://api.github.com/repos/sympy/sympy/issues/4724/events",
    "html_url": "https://github.com/sympy/sympy/issues/4724",
    "id": "28950057",
    "labels": Array [
      Object {
        "color": "ededed",
        "default": true,
        "id": 84627344,
        "name": "bug",
        "url": "https://api.github.com/repos/sympy/sympy/labels/bug",
      },
      Object {
        "color": "ededed",
        "default": false,
        "id": 84627341,
        "name": "imported",
        "url": "https://api.github.com/repos/sympy/sympy/labels/imported",
      },
      Object {
        "color": "fbca04",
        "default": false,
        "id": 191924,
        "name": "Needs Better Patch",
        "url": "https://api.github.com/repos/sympy/sympy/labels/Needs%20Better%20Patch",
      },
      Object {
        "color": "0000FF",
        "default": false,
        "id": 84627362,
        "name": "parsing",
        "url": "https://api.github.com/repos/sympy/sympy/labels/parsing",
      },
      Object {
        "color": "d4c5f9",
        "default": false,
        "id": 84627345,
        "name": "valid",
        "url": "https://api.github.com/repos/sympy/sympy/labels/valid",
      },
    ],
    "labels_url": "https://api.github.com/repos/sympy/sympy/issues/4724/labels{/name}",
    "locked": false,
    "milestone": null,
    "number": 4724,
    "repository_url": "https://api.github.com/repos/sympy/sympy",
    "score": 0.33729702,
    "state": "open",
    "title": "sympify of logical operations gets confused with ==",
    "updated_at": "2015-04-17T16:58:12Z",
    "url": "https://api.github.com/repos/sympy/sympy/issues/4724",
    "user": Object {
      "avatar_url": "https://avatars3.githubusercontent.com/u/6188475?v=3",
      "events_url": "https://api.github.com/users/sympy-issue-migrator/events{/privacy}",
      "followers_url": "https://api.github.com/users/sympy-issue-migrator/followers",
      "following_url": "https://api.github.com/users/sympy-issue-migrator/following{/other_user}",
      "gists_url": "https://api.github.com/users/sympy-issue-migrator/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/sympy-issue-migrator",
      "id": 6188475,
      "login": "sympy-issue-migrator",
      "organizations_url": "https://api.github.com/users/sympy-issue-migrator/orgs",
      "received_events_url": "https://api.github.com/users/sympy-issue-migrator/received_events",
      "repos_url": "https://api.github.com/users/sympy-issue-migrator/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/sympy-issue-migrator/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/sympy-issue-migrator/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/sympy-issue-migrator",
    },
  },
  Object {
    "assignee": null,
    "assignees": Array [],
    "body": "bc.. From our feedback:

OK.  Thanks.  I finally got it by using jython 2.50b rather
than the production version of jython and then running
the Windows installer of sympy and issuing 'jython setup.py'
where setup.py is in sympy.  Suggest that an actual console
session log showing the installation of jython and sympy be
included in the installation documentation to clarify
the steps, which versions of each component are required,
etc.

p. Original issue for \\"#4331\\":https://github.com/sympy/sympy/issues/4331: \\"http://code.google.com/p/sympy/issues/detail?id=1232\\":http://code.google.com/p/sympy/issues/detail?id=1232

p. Original author: \\"https://code.google.com/u/104039945248245758823/\\":https://code.google.com/u/104039945248245758823/
",
    "closed_at": null,
    "comments": 6,
    "comments_url": "https://api.github.com/repos/sympy/sympy/issues/4331/comments",
    "created_at": "2008-12-06T01:02:51Z",
    "events_url": "https://api.github.com/repos/sympy/sympy/issues/4331/events",
    "html_url": "https://github.com/sympy/sympy/issues/4331",
    "id": "28949579",
    "labels": Array [
      Object {
        "color": "800080",
        "default": false,
        "id": 84627441,
        "name": "Alternate Python",
        "url": "https://api.github.com/repos/sympy/sympy/labels/Alternate%20Python",
      },
      Object {
        "color": "ededed",
        "default": true,
        "id": 84627344,
        "name": "bug",
        "url": "https://api.github.com/repos/sympy/sympy/labels/bug",
      },
      Object {
        "color": "009800",
        "default": false,
        "id": 75782144,
        "name": "Easy to Fix",
        "url": "https://api.github.com/repos/sympy/sympy/labels/Easy%20to%20Fix",
      },
      Object {
        "color": "ededed",
        "default": false,
        "id": 84627341,
        "name": "imported",
        "url": "https://api.github.com/repos/sympy/sympy/labels/imported",
      },
      Object {
        "color": "d4c5f9",
        "default": false,
        "id": 84627345,
        "name": "valid",
        "url": "https://api.github.com/repos/sympy/sympy/labels/valid",
      },
    ],
    "labels_url": "https://api.github.com/repos/sympy/sympy/issues/4331/labels{/name}",
    "locked": false,
    "milestone": null,
    "number": 4331,
    "repository_url": "https://api.github.com/repos/sympy/sympy",
    "score": 0.33729702,
    "state": "open",
    "title": "add jython howto to our docs",
    "updated_at": "2015-04-17T16:58:12Z",
    "url": "https://api.github.com/repos/sympy/sympy/issues/4331",
    "user": Object {
      "avatar_url": "https://avatars0.githubusercontent.com/u/20568?v=3",
      "events_url": "https://api.github.com/users/certik/events{/privacy}",
      "followers_url": "https://api.github.com/users/certik/followers",
      "following_url": "https://api.github.com/users/certik/following{/other_user}",
      "gists_url": "https://api.github.com/users/certik/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/certik",
      "id": 20568,
      "login": "certik",
      "organizations_url": "https://api.github.com/users/certik/orgs",
      "received_events_url": "https://api.github.com/users/certik/received_events",
      "repos_url": "https://api.github.com/users/certik/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/certik/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/certik/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/certik",
    },
  },
  Object {
    "assignee": null,
    "assignees": Array [],
    "body": "\`\`\`
Intersect seems to generally work incorrectly, example is:

print intersection(Segment(Point(5, -0.730642868656981), Point(6,
-0.0988049466141603)), Segment(Point(5.5, -2.74551357555141), Point(5.5, 1)))

So the intersection should be at about (5.5, -1.4)?

Seems to be broken in general, works rarely.  I can give more example code.

Sorry if I'm overtired right now and doing something blatantly stupid.
\`\`\`

Original issue for #4748: http://code.google.com/p/sympy/issues/detail?id=1649
Original author: https://code.google.com/u/106893876112355965992/
",
    "closed_at": null,
    "comments": 4,
    "comments_url": "https://api.github.com/repos/sympy/sympy/issues/4748/comments",
    "created_at": "2009-09-17T11:53:10Z",
    "events_url": "https://api.github.com/repos/sympy/sympy/issues/4748/events",
    "html_url": "https://github.com/sympy/sympy/issues/4748",
    "id": "28950088",
    "labels": Array [
      Object {
        "color": "ededed",
        "default": true,
        "id": 84627344,
        "name": "bug",
        "url": "https://api.github.com/repos/sympy/sympy/labels/bug",
      },
      Object {
        "color": "ededed",
        "default": false,
        "id": 84627341,
        "name": "imported",
        "url": "https://api.github.com/repos/sympy/sympy/labels/imported",
      },
    ],
    "labels_url": "https://api.github.com/repos/sympy/sympy/issues/4748/labels{/name}",
    "locked": false,
    "milestone": null,
    "number": 4748,
    "repository_url": "https://api.github.com/repos/sympy/sympy",
    "score": 0.1793177,
    "state": "open",
    "title": "Intersect bug (feature)",
    "updated_at": "2015-04-17T16:58:12Z",
    "url": "https://api.github.com/repos/sympy/sympy/issues/4748",
    "user": Object {
      "avatar_url": "https://avatars2.githubusercontent.com/u/134333?v=3",
      "events_url": "https://api.github.com/users/hut3/events{/privacy}",
      "followers_url": "https://api.github.com/users/hut3/followers",
      "following_url": "https://api.github.com/users/hut3/following{/other_user}",
      "gists_url": "https://api.github.com/users/hut3/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/hut3",
      "id": 134333,
      "login": "hut3",
      "organizations_url": "https://api.github.com/users/hut3/orgs",
      "received_events_url": "https://api.github.com/users/hut3/received_events",
      "repos_url": "https://api.github.com/users/hut3/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/hut3/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/hut3/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/hut3",
    },
  },
  Object {
    "assignee": null,
    "assignees": Array [],
    "body": "bc.. I was reviving my efforts to compile functions to machine code and got this
(you will probably need the latest revision):

Traceback (most recent call last):
  File \\"/home/one/src/sympy/compilef.py\\", line 331, in <module>
    benchmark(f)
  File \\"/home/one/src/sympy/compilef.py\\", line 302, in benchmark
    pf = lambdify(var, f)
  File
\\"/usr/local/lib/python2.5/site-packages/sympy/utilities/lambdify.py\\", line
169, in lambdify
    buf = _get_namespace(m)
  File
\\"/usr/local/lib/python2.5/site-packages/sympy/utilities/lambdify.py\\", line
184, in _get_namespace
    _import(m)
  File
\\"/usr/local/lib/python2.5/site-packages/sympy/utilities/lambdify.py\\", line
86, in _import
    raise ImportError, \\"Can't import %s with command %s\\"%(modulename,
NameError: name 'modulename' is not defined

It seems to fail at raising an exception because uses a non-existent name.
I think that it tries to analyze the namespace and fails due to being used
from a function, but I'm not sure. I did not yet look into lambdify's
implementation and I still need to figure out what exactly causes the bug.

At least the NameError should be fixed.

p. Original issue for \\"#3953\\":https://github.com/sympy/sympy/issues/3953: \\"http://code.google.com/p/sympy/issues/detail?id=854\\":http://code.google.com/p/sympy/issues/detail?id=854

p. Original author: \\"https://code.google.com/u/Vinzent.Steinberg@gmail.com/\\":https://code.google.com/u/Vinzent.Steinberg@gmail.com/
",
    "closed_at": null,
    "comments": 15,
    "comments_url": "https://api.github.com/repos/sympy/sympy/issues/3953/comments",
    "created_at": "2008-05-24T00:21:19Z",
    "events_url": "https://api.github.com/repos/sympy/sympy/issues/3953/events",
    "html_url": "https://github.com/sympy/sympy/issues/3953",
    "id": "28949129",
    "labels": Array [
      Object {
        "color": "ededed",
        "default": true,
        "id": 84627344,
        "name": "bug",
        "url": "https://api.github.com/repos/sympy/sympy/labels/bug",
      },
      Object {
        "color": "ededed",
        "default": false,
        "id": 84627341,
        "name": "imported",
        "url": "https://api.github.com/repos/sympy/sympy/labels/imported",
      },
    ],
    "labels_url": "https://api.github.com/repos/sympy/sympy/issues/3953/labels{/name}",
    "locked": false,
    "milestone": null,
    "number": 3953,
    "repository_url": "https://api.github.com/repos/sympy/sympy",
    "score": 0.107590616,
    "state": "open",
    "title": "new lambdify fails to raise an exception",
    "updated_at": "2015-04-17T16:58:11Z",
    "url": "https://api.github.com/repos/sympy/sympy/issues/3953",
    "user": Object {
      "avatar_url": "https://avatars1.githubusercontent.com/u/33460?v=3",
      "events_url": "https://api.github.com/users/vks/events{/privacy}",
      "followers_url": "https://api.github.com/users/vks/followers",
      "following_url": "https://api.github.com/users/vks/following{/other_user}",
      "gists_url": "https://api.github.com/users/vks/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/vks",
      "id": 33460,
      "login": "vks",
      "organizations_url": "https://api.github.com/users/vks/orgs",
      "received_events_url": "https://api.github.com/users/vks/received_events",
      "repos_url": "https://api.github.com/users/vks/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/vks/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/vks/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/vks",
    },
  },
  Object {
    "assignee": null,
    "assignees": Array [],
    "body": "## bc.. In [39]: preview(x**x)

ImportError                               Traceback (most recent call last)

/home/one/<ipython console> in <module>()

/usr/local/lib/python2.5/site-packages/sympy-0.5.15-py2.5.egg/sympy/printing/preview.pyc
in preview(expr, output, viewer, euler)
     53     # we don't want to depend on anything not in the
     54     # standard library with SymPy by default
---> 55     import pexpect
     56
     57     special = [ 'pyglet' ]

ImportError: No module named pexpect

p. Original issue for \\"#3971\\":https://github.com/sympy/sympy/issues/3971: \\"http://code.google.com/p/sympy/issues/detail?id=872\\":http://code.google.com/p/sympy/issues/detail?id=872

p. Original author: \\"https://code.google.com/u/Vinzent.Steinberg@gmail.com/\\":https://code.google.com/u/Vinzent.Steinberg@gmail.com/
",
    "closed_at": null,
    "comments": 23,
    "comments_url": "https://api.github.com/repos/sympy/sympy/issues/3971/comments",
    "created_at": "2008-06-03T18:43:56Z",
    "events_url": "https://api.github.com/repos/sympy/sympy/issues/3971/events",
    "html_url": "https://github.com/sympy/sympy/issues/3971",
    "id": "28949151",
    "labels": Array [
      Object {
        "color": "ededed",
        "default": true,
        "id": 84627344,
        "name": "bug",
        "url": "https://api.github.com/repos/sympy/sympy/labels/bug",
      },
      Object {
        "color": "ededed",
        "default": false,
        "id": 84627341,
        "name": "imported",
        "url": "https://api.github.com/repos/sympy/sympy/labels/imported",
      },
      Object {
        "color": "d4c5f9",
        "default": false,
        "id": 84627345,
        "name": "valid",
        "url": "https://api.github.com/repos/sympy/sympy/labels/valid",
      },
    ],
    "labels_url": "https://api.github.com/repos/sympy/sympy/issues/3971/labels{/name}",
    "locked": false,
    "milestone": null,
    "number": 3971,
    "repository_url": "https://api.github.com/repos/sympy/sympy",
    "score": 0.4166967,
    "state": "open",
    "title": "remove dependency on pexpect and add support for Mathtex",
    "updated_at": "2015-04-17T16:58:11Z",
    "url": "https://api.github.com/repos/sympy/sympy/issues/3971",
    "user": Object {
      "avatar_url": "https://avatars1.githubusercontent.com/u/33460?v=3",
      "events_url": "https://api.github.com/users/vks/events{/privacy}",
      "followers_url": "https://api.github.com/users/vks/followers",
      "following_url": "https://api.github.com/users/vks/following{/other_user}",
      "gists_url": "https://api.github.com/users/vks/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/vks",
      "id": 33460,
      "login": "vks",
      "organizations_url": "https://api.github.com/users/vks/orgs",
      "received_events_url": "https://api.github.com/users/vks/received_events",
      "repos_url": "https://api.github.com/users/vks/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/vks/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/vks/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/vks",
    },
  },
  Object {
    "assignee": null,
    "assignees": Array [],
    "body": "bc.. >>> from sympy import *
 Traceback (most recent call last):
  File \\"C:\\\\Dokumente und Einstellungen\\\\Vinzent\\\\Desktop\\\\newmax.py\\", line 1,
in <module>
    from sympy import *
  File \\"C:\\\\Python25\\\\Lib\\\\site-packages\\\\sympy__init__.py\\", line 22, in <module>
    from sympy.core import *
  File \\"C:\\\\Python25\\\\Lib\\\\site-packages\\\\sympy\\\\core__init__.py\\", line 4, in
<module>
    from basic import Basic, S, C, sympify
  File \\"C:\\\\Python25\\\\Lib\\\\site-packages\\\\sympy\\\\core\\\\basic.py\\", line 5, in <module>
    import sympy.thirdparty.mpmath as mpmath
  File \\"C:\\\\Python25\\\\Lib\\\\site-packages\\\\sympy\\\\thirdparty\\\\mpmath__init__.py\\",
line 5, in <module>
    from mptypes import *
  File \\"C:\\\\Python25\\\\Lib\\\\site-packages\\\\sympy\\\\thirdparty\\\\mpmath\\\\mptypes.py\\",
line 17, in <module>
    from libmpc import *
  File \\"C:\\\\Python25\\\\Lib\\\\site-packages\\\\sympy\\\\thirdparty\\\\mpmath\\\\libmpc.py\\",
line 19, in <module>
    def mpc_add((a, b), (c, d), prec, rnd=round_fast):
NameError: name 'round_fast' is not defined

I installed latest revision via setup.py install on Windows. If this is due
to not removing sympy before, setup.py has to be fixed.

p. Original issue for \\"#3963\\":https://github.com/sympy/sympy/issues/3963: \\"http://code.google.com/p/sympy/issues/detail?id=864\\":http://code.google.com/p/sympy/issues/detail?id=864

p. Original author: \\"https://code.google.com/u/Vinzent.Steinberg@gmail.com/\\":https://code.google.com/u/Vinzent.Steinberg@gmail.com/
",
    "closed_at": null,
    "comments": 24,
    "comments_url": "https://api.github.com/repos/sympy/sympy/issues/3963/comments",
    "created_at": "2008-05-27T21:34:52Z",
    "events_url": "https://api.github.com/repos/sympy/sympy/issues/3963/events",
    "html_url": "https://github.com/sympy/sympy/issues/3963",
    "id": "28949140",
    "labels": Array [
      Object {
        "color": "ededed",
        "default": true,
        "id": 84627344,
        "name": "bug",
        "url": "https://api.github.com/repos/sympy/sympy/labels/bug",
      },
      Object {
        "color": "ededed",
        "default": false,
        "id": 84627341,
        "name": "imported",
        "url": "https://api.github.com/repos/sympy/sympy/labels/imported",
      },
      Object {
        "color": "d4c5f9",
        "default": false,
        "id": 84627345,
        "name": "valid",
        "url": "https://api.github.com/repos/sympy/sympy/labels/valid",
      },
    ],
    "labels_url": "https://api.github.com/repos/sympy/sympy/issues/3963/labels{/name}",
    "locked": false,
    "milestone": null,
    "number": 3963,
    "repository_url": "https://api.github.com/repos/sympy/sympy",
    "score": 0.26983762,
    "state": "open",
    "title": "fix upgrading via setup.py or add a big fat warning",
    "updated_at": "2015-04-17T16:58:11Z",
    "url": "https://api.github.com/repos/sympy/sympy/issues/3963",
    "user": Object {
      "avatar_url": "https://avatars1.githubusercontent.com/u/33460?v=3",
      "events_url": "https://api.github.com/users/vks/events{/privacy}",
      "followers_url": "https://api.github.com/users/vks/followers",
      "following_url": "https://api.github.com/users/vks/following{/other_user}",
      "gists_url": "https://api.github.com/users/vks/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/vks",
      "id": 33460,
      "login": "vks",
      "organizations_url": "https://api.github.com/users/vks/orgs",
      "received_events_url": "https://api.github.com/users/vks/received_events",
      "repos_url": "https://api.github.com/users/vks/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/vks/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/vks/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/vks",
    },
  },
  Object {
    "assignee": null,
    "assignees": Array [],
    "body": "bc.. Trying to use with IRONPython and get the error below:

  File C:\\\\Python24\\\\Lib\\\\site-packages\\\\sympy__init__.py, line 4, in 
Initialize
  File , line 0, in _stub_##2
  File C:\\\\Python24\\\\Lib\\\\site-packages\\\\sympy\\\\core__init__.py, line 26, in 
Initialize
AttributeError: 'dictproxy' object has no attribute 'get'

Any thoughts?

p. Original issue for \\"#3552\\":https://github.com/sympy/sympy/issues/3552: \\"http://code.google.com/p/sympy/issues/detail?id=453\\":http://code.google.com/p/sympy/issues/detail?id=453

p. Original author: \\"https://code.google.com/u/115961875564935506885/\\":https://code.google.com/u/115961875564935506885/
",
    "closed_at": null,
    "comments": 11,
    "comments_url": "https://api.github.com/repos/sympy/sympy/issues/3552/comments",
    "created_at": "2007-11-18T04:48:18Z",
    "events_url": "https://api.github.com/repos/sympy/sympy/issues/3552/events",
    "html_url": "https://github.com/sympy/sympy/issues/3552",
    "id": "28948669",
    "labels": Array [
      Object {
        "color": "800080",
        "default": false,
        "id": 84627441,
        "name": "Alternate Python",
        "url": "https://api.github.com/repos/sympy/sympy/labels/Alternate%20Python",
      },
      Object {
        "color": "ededed",
        "default": true,
        "id": 84627344,
        "name": "bug",
        "url": "https://api.github.com/repos/sympy/sympy/labels/bug",
      },
      Object {
        "color": "ededed",
        "default": false,
        "id": 84627341,
        "name": "imported",
        "url": "https://api.github.com/repos/sympy/sympy/labels/imported",
      },
      Object {
        "color": "d4c5f9",
        "default": false,
        "id": 84627345,
        "name": "valid",
        "url": "https://api.github.com/repos/sympy/sympy/labels/valid",
      },
    ],
    "labels_url": "https://api.github.com/repos/sympy/sympy/issues/3552/labels{/name}",
    "locked": false,
    "milestone": null,
    "number": 3552,
    "repository_url": "https://api.github.com/repos/sympy/sympy",
    "score": 0.3513895,
    "state": "open",
    "title": "ironpython: AttributeError: 'dictproxy' object has no attribute 'get'",
    "updated_at": "2015-04-17T16:58:11Z",
    "url": "https://api.github.com/repos/sympy/sympy/issues/3552",
    "user": Object {
      "avatar_url": "https://avatars3.githubusercontent.com/u/6188475?v=3",
      "events_url": "https://api.github.com/users/sympy-issue-migrator/events{/privacy}",
      "followers_url": "https://api.github.com/users/sympy-issue-migrator/followers",
      "following_url": "https://api.github.com/users/sympy-issue-migrator/following{/other_user}",
      "gists_url": "https://api.github.com/users/sympy-issue-migrator/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/sympy-issue-migrator",
      "id": 6188475,
      "login": "sympy-issue-migrator",
      "organizations_url": "https://api.github.com/users/sympy-issue-migrator/orgs",
      "received_events_url": "https://api.github.com/users/sympy-issue-migrator/received_events",
      "repos_url": "https://api.github.com/users/sympy-issue-migrator/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/sympy-issue-migrator/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/sympy-issue-migrator/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/sympy-issue-migrator",
    },
  },
  Object {
    "assignee": null,
    "assignees": Array [],
    "body": "bc.. $ ./setup.py install  
./setup.py: line 1: from: command not found  
: command not found  
'/setup.py: line 3: syntax error near unexpected token \`name='mpmath',
'/setup.py: line 3:\`setup(name='mpmath',  
$ python setup.py install
running install  
running build  
running build_py 
[...]                               

This is trivial, simple #!python in the first line would do the job.

p. Original issue for \\"#77\\":https://github.com/fredrik-johansson/mpmath/issues/77: \\"http://code.google.com/p/mpmath/issues/detail?id=37\\":http://code.google.com/p/mpmath/issues/detail?id=37

p. Original author: \\"https://code.google.com/u/Vinzent.Steinberg@gmail.com/\\":https://code.google.com/u/Vinzent.Steinberg@gmail.com/
",
    "closed_at": null,
    "comments": 9,
    "comments_url": "https://api.github.com/repos/fredrik-johansson/mpmath/issues/77/comments",
    "created_at": "2008-04-24T01:23:02Z",
    "events_url": "https://api.github.com/repos/fredrik-johansson/mpmath/issues/77/events",
    "html_url": "https://github.com/fredrik-johansson/mpmath/issues/77",
    "id": "32125397",
    "labels": Array [
      Object {
        "color": "ededed",
        "default": true,
        "id": 94738783,
        "name": "bug",
        "url": "https://api.github.com/repos/fredrik-johansson/mpmath/labels/bug",
      },
      Object {
        "color": "ededed",
        "default": false,
        "id": 94738780,
        "name": "imported",
        "url": "https://api.github.com/repos/fredrik-johansson/mpmath/labels/imported",
      },
      Object {
        "color": "ededed",
        "default": false,
        "id": 94738781,
        "name": "Priority-Medium",
        "url": "https://api.github.com/repos/fredrik-johansson/mpmath/labels/Priority-Medium",
      },
    ],
    "labels_url": "https://api.github.com/repos/fredrik-johansson/mpmath/issues/77/labels{/name}",
    "locked": false,
    "milestone": null,
    "number": 77,
    "repository_url": "https://api.github.com/repos/fredrik-johansson/mpmath",
    "score": 0.25339288,
    "state": "open",
    "title": "setup.py lacks shebang",
    "updated_at": "2014-04-24T07:14:21Z",
    "url": "https://api.github.com/repos/fredrik-johansson/mpmath/issues/77",
    "user": Object {
      "avatar_url": "https://avatars1.githubusercontent.com/u/33460?v=3",
      "events_url": "https://api.github.com/users/vks/events{/privacy}",
      "followers_url": "https://api.github.com/users/vks/followers",
      "following_url": "https://api.github.com/users/vks/following{/other_user}",
      "gists_url": "https://api.github.com/users/vks/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/vks",
      "id": 33460,
      "login": "vks",
      "organizations_url": "https://api.github.com/users/vks/orgs",
      "received_events_url": "https://api.github.com/users/vks/received_events",
      "repos_url": "https://api.github.com/users/vks/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/vks/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/vks/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/vks",
    },
  },
  Object {
    "assignee": null,
    "assignees": Array [],
    "body": "In my first test pycallpraph barfed spectacularily (on windows XP/german), because it just fed the pathname for the picture - containing spaces - to dot. The easiest way to fix that is using the subprocess module (in the standard library since python 2.4).

(My version is actually 0.5.1 installed via easy_install but I can't select it under \\"Version\\" for this ticket)
",
    "closed_at": null,
    "comments": 0,
    "comments_url": "https://api.github.com/repos/gak/pycallgraph/issues/84/comments",
    "created_at": "2009-08-12T12:20:44Z",
    "events_url": "https://api.github.com/repos/gak/pycallgraph/issues/84/events",
    "html_url": "https://github.com/gak/pycallgraph/issues/84",
    "id": "46451",
    "labels": Array [
      Object {
        "color": "5319e7",
        "default": true,
        "id": 54208387,
        "name": "bug",
        "url": "https://api.github.com/repos/gak/pycallgraph/labels/bug",
      },
    ],
    "labels_url": "https://api.github.com/repos/gak/pycallgraph/issues/84/labels{/name}",
    "locked": false,
    "milestone": Object {
      "closed_at": null,
      "closed_issues": 0,
      "created_at": "2013-07-24T08:58:17Z",
      "creator": Object {
        "avatar_url": "https://avatars0.githubusercontent.com/u/31338?v=3",
        "events_url": "https://api.github.com/users/gak/events{/privacy}",
        "followers_url": "https://api.github.com/users/gak/followers",
        "following_url": "https://api.github.com/users/gak/following{/other_user}",
        "gists_url": "https://api.github.com/users/gak/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/gak",
        "id": 31338,
        "login": "gak",
        "organizations_url": "https://api.github.com/users/gak/orgs",
        "received_events_url": "https://api.github.com/users/gak/received_events",
        "repos_url": "https://api.github.com/users/gak/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/gak/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/gak/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/gak",
      },
      "description": "Realtime callgraphs",
      "due_on": "2014-02-28T08:00:00Z",
      "html_url": "https://github.com/gak/pycallgraph/milestone/2",
      "id": 385685,
      "labels_url": "https://api.github.com/repos/gak/pycallgraph/milestones/2/labels",
      "number": 2,
      "open_issues": 10,
      "state": "open",
      "title": "1.1.0",
      "updated_at": "2013-12-13T21:16:10Z",
      "url": "https://api.github.com/repos/gak/pycallgraph/milestones/2",
    },
    "number": 84,
    "repository_url": "https://api.github.com/repos/gak/pycallgraph",
    "score": 0.46282244,
    "state": "open",
    "title": "Escape pathnames for dot",
    "updated_at": "2013-09-14T06:35:51Z",
    "url": "https://api.github.com/repos/gak/pycallgraph/issues/84",
    "user": Object {
      "avatar_url": "https://avatars0.githubusercontent.com/u/31338?v=3",
      "events_url": "https://api.github.com/users/gak/events{/privacy}",
      "followers_url": "https://api.github.com/users/gak/followers",
      "following_url": "https://api.github.com/users/gak/following{/other_user}",
      "gists_url": "https://api.github.com/users/gak/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/gak",
      "id": 31338,
      "login": "gak",
      "organizations_url": "https://api.github.com/users/gak/orgs",
      "received_events_url": "https://api.github.com/users/gak/received_events",
      "repos_url": "https://api.github.com/users/gak/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/gak/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gak/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/gak",
    },
  },
  Object {
    "assignee": null,
    "assignees": Array [],
    "body": "I am not totally sure about the new line numbers. What font are you using to display them? Arial Unicode doesn't support them (and it's the most comprehensive windows font I know of).

If we can find a commonly distributed windows font that supports them then no problem (we can use html font tags) but otherwise the \\"(21)\\" style is probably better.
",
    "closed_at": null,
    "comments": 15,
    "comments_url": "https://api.github.com/repos/batterseapower/pinyin-toolkit/issues/132/comments",
    "created_at": "2009-07-12T20:10:41Z",
    "events_url": "https://api.github.com/repos/batterseapower/pinyin-toolkit/issues/132/events",
    "html_url": "https://github.com/batterseapower/pinyin-toolkit/issues/132",
    "id": "35802",
    "labels": Array [
      Object {
        "color": "ff0000",
        "default": true,
        "id": 6425,
        "name": "bug",
        "url": "https://api.github.com/repos/batterseapower/pinyin-toolkit/labels/bug",
      },
    ],
    "labels_url": "https://api.github.com/repos/batterseapower/pinyin-toolkit/issues/132/labels{/name}",
    "locked": false,
    "milestone": null,
    "number": 132,
    "repository_url": "https://api.github.com/repos/batterseapower/pinyin-toolkit",
    "score": 0.75318795,
    "state": "open",
    "title": "Line Number Indexes Beyond 20 Not Displayed",
    "updated_at": "2009-07-19T09:23:43Z",
    "url": "https://api.github.com/repos/batterseapower/pinyin-toolkit/issues/132",
    "user": Object {
      "avatar_url": "https://avatars0.githubusercontent.com/u/90254?v=3",
      "events_url": "https://api.github.com/users/Nick3C/events{/privacy}",
      "followers_url": "https://api.github.com/users/Nick3C/followers",
      "following_url": "https://api.github.com/users/Nick3C/following{/other_user}",
      "gists_url": "https://api.github.com/users/Nick3C/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/Nick3C",
      "id": 90254,
      "login": "Nick3C",
      "organizations_url": "https://api.github.com/users/Nick3C/orgs",
      "received_events_url": "https://api.github.com/users/Nick3C/received_events",
      "repos_url": "https://api.github.com/users/Nick3C/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/Nick3C/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Nick3C/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/Nick3C",
    },
  },
  Object {
    "assignee": null,
    "assignees": Array [],
    "body": "Systray icon remains after the application is closed. Mousover makes it disappear.
Noticed on windows, not sure if it's the same under Linux as well...
",
    "closed_at": null,
    "comments": 0,
    "comments_url": "https://api.github.com/repos/imrehg/minibook/issues/7/comments",
    "created_at": "2009-05-19T15:50:52Z",
    "events_url": "https://api.github.com/repos/imrehg/minibook/issues/7/events",
    "html_url": "https://github.com/imrehg/minibook/issues/7",
    "id": "16922",
    "labels": Array [
      Object {
        "color": "e81010",
        "default": false,
        "id": 4944,
        "name": "Bug",
        "url": "https://api.github.com/repos/imrehg/minibook/labels/Bug",
      },
    ],
    "labels_url": "https://api.github.com/repos/imrehg/minibook/issues/7/labels{/name}",
    "locked": false,
    "milestone": null,
    "number": 7,
    "repository_url": "https://api.github.com/repos/imrehg/minibook",
    "score": 0.8229122,
    "state": "open",
    "title": "Systray icon remains after application close",
    "updated_at": "2009-06-07T05:32:03Z",
    "url": "https://api.github.com/repos/imrehg/minibook/issues/7",
    "user": Object {
      "avatar_url": "https://avatars3.githubusercontent.com/u/38863?v=3",
      "events_url": "https://api.github.com/users/imrehg/events{/privacy}",
      "followers_url": "https://api.github.com/users/imrehg/followers",
      "following_url": "https://api.github.com/users/imrehg/following{/other_user}",
      "gists_url": "https://api.github.com/users/imrehg/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/imrehg",
      "id": 38863,
      "login": "imrehg",
      "organizations_url": "https://api.github.com/users/imrehg/orgs",
      "received_events_url": "https://api.github.com/users/imrehg/received_events",
      "repos_url": "https://api.github.com/users/imrehg/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/imrehg/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/imrehg/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/imrehg",
    },
  },
  Object {
    "assignee": null,
    "assignees": Array [],
    "body": "Currently icon only resides in status bar, but no icon for the task bar part.
",
    "closed_at": null,
    "comments": 1,
    "comments_url": "https://api.github.com/repos/imrehg/minibook/issues/2/comments",
    "created_at": "2009-05-16T01:21:33Z",
    "events_url": "https://api.github.com/repos/imrehg/minibook/issues/2/events",
    "html_url": "https://github.com/imrehg/minibook/issues/2",
    "id": "15709",
    "labels": Array [
      Object {
        "color": "e81010",
        "default": false,
        "id": 4944,
        "name": "Bug",
        "url": "https://api.github.com/repos/imrehg/minibook/labels/Bug",
      },
    ],
    "labels_url": "https://api.github.com/repos/imrehg/minibook/issues/2/labels{/name}",
    "locked": false,
    "milestone": null,
    "number": 2,
    "repository_url": "https://api.github.com/repos/imrehg/minibook",
    "score": 0.71719646,
    "state": "open",
    "title": "Icon in app name",
    "updated_at": "2009-06-07T05:32:03Z",
    "url": "https://api.github.com/repos/imrehg/minibook/issues/2",
    "user": Object {
      "avatar_url": "https://avatars3.githubusercontent.com/u/38863?v=3",
      "events_url": "https://api.github.com/users/imrehg/events{/privacy}",
      "followers_url": "https://api.github.com/users/imrehg/followers",
      "following_url": "https://api.github.com/users/imrehg/following{/other_user}",
      "gists_url": "https://api.github.com/users/imrehg/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/imrehg",
      "id": 38863,
      "login": "imrehg",
      "organizations_url": "https://api.github.com/users/imrehg/orgs",
      "received_events_url": "https://api.github.com/users/imrehg/received_events",
      "repos_url": "https://api.github.com/users/imrehg/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/imrehg/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/imrehg/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/imrehg",
    },
  },
  Object {
    "assignee": null,
    "assignees": Array [],
    "body": "Check proper threading enter() and leave() for the code, not to have the entire program inside that...
",
    "closed_at": null,
    "comments": 0,
    "comments_url": "https://api.github.com/repos/imrehg/mitter-fork/issues/2/comments",
    "created_at": "2009-05-26T04:40:00Z",
    "events_url": "https://api.github.com/repos/imrehg/mitter-fork/issues/2/events",
    "html_url": "https://github.com/imrehg/mitter-fork/issues/2",
    "id": "19353",
    "labels": Array [
      Object {
        "color": "f70000",
        "default": false,
        "id": 5812,
        "name": "Bug",
        "url": "https://api.github.com/repos/imrehg/mitter-fork/labels/Bug",
      },
    ],
    "labels_url": "https://api.github.com/repos/imrehg/mitter-fork/issues/2/labels{/name}",
    "locked": false,
    "milestone": null,
    "number": 2,
    "repository_url": "https://api.github.com/repos/imrehg/mitter-fork",
    "score": 6.2315407,
    "state": "open",
    "title": "Threading fix for windows",
    "updated_at": "2009-05-26T04:40:00Z",
    "url": "https://api.github.com/repos/imrehg/mitter-fork/issues/2",
    "user": Object {
      "avatar_url": "https://avatars3.githubusercontent.com/u/38863?v=3",
      "events_url": "https://api.github.com/users/imrehg/events{/privacy}",
      "followers_url": "https://api.github.com/users/imrehg/followers",
      "following_url": "https://api.github.com/users/imrehg/following{/other_user}",
      "gists_url": "https://api.github.com/users/imrehg/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/imrehg",
      "id": 38863,
      "login": "imrehg",
      "organizations_url": "https://api.github.com/users/imrehg/orgs",
      "received_events_url": "https://api.github.com/users/imrehg/received_events",
      "repos_url": "https://api.github.com/users/imrehg/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/imrehg/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/imrehg/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/imrehg",
    },
  },
]
`;
